# Generated by Django 5.1.3 on 2024-11-14 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
    ]
